services:

  db:
    image: postgres:16
    container_name: postgres
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

# Redis service removed - no longer needed without Celery

  web:
    build:
      context: ./crm
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/crm
    env_file:
      - .env
    depends_on:
      - db

# Celery service removed for Railway free tier compatibility

volumes:
  pgdata:
