# Generated by Django 4.2 on 2024-03-10 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_event_attendee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Record',
            new_name='Contact',
        ),
    ]
