# Generated by Django 4.2 on 2025-03-29 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0003_project_alter_event_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Task',
        ),
    ]
