# Generated by Django 4.2 on 2025-03-30 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_basetask_onboardingstep_onboardingtasktemplate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_progress', to='webapp.projectmembership')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.onboardingtask')),
            ],
            options={
                'unique_together': {('membership', 'task')},
            },
        ),
    ]
