# Generated by Django 4.2 on 2025-04-10 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_onboardingprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmembership',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_manage_users',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userrole',
            name='can_view_statistics',
            field=models.BooleanField(default=False),
        ),
    ]
